[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@thirdweb-dev/=node_modules/@thirdweb-dev/',
    'forge-std/=lib/forge-std/src/'
]
solc = "0.8.28" 